### PR TITLE
INI: fix metadata collection on platforms with 64-bit dev_t

### LINKED ISSUE #37: INI metadata reading does not work on FreeBSD/i386
Inside the `collect_metadata()` function there is a block of code that looks like:

```
   206          if (file_stats.st_dev > ULONG_MAX) {
-> 207              TRACE_ERROR_NUMBER("Device is out of range", ERANGE);
   208              col_destroy_collection(metasec);
   209              return ERANGE;
   210          }
```

The `st_dev` field is of type `dev_t`, which is apparently 64-bit even on 32-bit systems:

```
print file_stats.st_dev
(dev_t) 18446744071681212351
```

This obviously fails the check, which leads to `config_from_file_with_metadata()` to fail. Not sure how to properly fix this, hence no PR.

### PR DESCRIPTION
**Pull request by alexey-tikhonov**
Resolves: https://github.com/SSSD/ding-libs/issues/37

Assisted-By: Claude Code (Opus 4.6)

### CODE REVIEW

**Comment by alexey-tikhonov** [comment]
@arrowd, could you please test this?

File: ini/ini_metadata.c [hunk 1]
```diff
@@ -197,23 +197,11 @@ int collect_metadata(uint32_t metaflags,
             return error;
         }
 
-        /* The device ID can actualy be bigger than
-         * 32-bits according to the type sizes.
-         * However it is probaly not going to happen
-         * on a real system.
```
Comment (arrowd) [inline ini/ini_metadata.c:203]: Ha!

**Review by arrowd — COMMENTED** [review]
Yes, I confirm that this change fixes the issue for me. Thank you!

**Comment by alexey-tikhonov** [comment]
(rebased)

File: ini/ini_metadata.c [hunk 2]
```diff
@@ -445,8 +433,8 @@ static unsigned long get_checked_value(struct collection_item *metadata,
         return 0;
     }
 
-    value = get_ulong_config_value(item, 1, -1, &error);
-    if ((error) || (value == -1)) {
+    value = (unsigned long long)get_uint64_config_value(item, 1, 0, &error);
```
Comment (sumit-bose) [inline ini/ini_metadata.c]: Hi,

wouldn't it be easier to make the variables and return value `uint64_t` explicitly? Or is there a reason you prefer `unsigned long long` ?

For the string conversion the `long long` casts are ok imo, because they just have to be sufficiently large.

bye,
Sumit

**Review by thalman — APPROVED** [review]
LGTM

File: ini/ini_metadata.c (hunk 2 above)
Comment (alexey-tikhonov) [reply ini/ini_metadata.c]: tl,dr: if you have a very strong preference, I can change to `uint64_t`

Formally, there are no guarantees for 'st_dev' type.
`long long` must be **at least** 64 bits wide.
If we imagine a platform, where 'st_dev' is 128 bits, using `uint64_t` will fail and using 'long long' have a chance to work.

Practically no difference, of course.

Comment (sumit-bose) [reply ini/ini_metadata.c]: Hi,

but wouldn't it be better then to make `get_ullong_config_value()` public because `get_uint64_config_value()` would return only `uint64_t`?

bye,
Sumit

Comment (alexey-tikhonov) [reply ini/ini_metadata.c]: Ah, got it...
Well, changing public API for this sake of this fix doesn't look justified.
I'll change to using `uint64_t`

Comment (alexey-tikhonov) [reply ini/ini_metadata.c]: Updated.

Comment (sumit-bose) [reply ini/ini_metadata.c]: Thanks.

**Review by sumit-bose — APPROVED** [review]
Hi,

thank you for the update, I have no further comments, ACK.

bye,
Sumit

**Comment by arrowd** [comment]
Are there plans to make a release containing this fix?

**Comment by alexey-tikhonov** [comment]
> Are there plans to make a release containing this fix?

Frankly I didn't plan so for the sake of this single patch...

**Comment by arrowd** [comment]
No prob, I already pulled this change downstream.
